### PR TITLE
Added past inflection

### PR DESCRIPTION
**Pull request by nawafnaim**

### CODE REVIEW

**Comment by nawafnaim** [comment]
Just realized that converting regular participles to past won't work with the current implementation. I'll update this PR with a fix soon (insha Allah).

**Comment by gmosx** [comment]
OK, waiting for the updated PR then.

On Wed, Apr 1, 2015 at 8:02 PM, Nawaf Alsulami notifications@github.com
wrote:

> Just realized that converting regular participles to past won't work with
> the current implementation. I'll update this PR with a fix soon (insha
> Allah).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gmosx/dart-inflection/pull/10#issuecomment-88548721.

## 

http://www.gmosx.com

**Comment by nawafnaim** [comment]
Fixed.

**Comment by nawafnaim** [comment]
Just found another problem. But should be easy to fix.

**Comment by nawafnaim** [comment]
done.

**Comment by gmosx** [comment]
For some reason past_test runs very slow, any idea why?

**Comment by nawafnaim** [comment]
How much slow compared with singular-plural inflection code? 

I suspect the reason for any observed slower performance may be due to the larger number of irregular cases of past inflection compared with plural inflection. See `irregular_past_verbs.dart`.

**Pull request merged**
